name: Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install and build
        run: |
          npm install
          npm run lint
          npm run build
